iwyu improvements and move raw-package impl to .cc

diff --git a/build-aux/iwyu b/build-aux/iwyu
--- a/build-aux/iwyu
+++ b/build-aux/iwyu
@@ -1,7 +1,8 @@
 #! /usr/bin/env bash
 # ============================================================================ #
 #
-# Wraps the \`include-what-you-use' executable our settings and options.
+# Wraps the `iwyu_tool.py'/`include-what-you-use' executable our settings
+# and options.
 #
 #
 # ---------------------------------------------------------------------------- #
@@ -14,7 +15,7 @@ set -o pipefail;
 
 _as_me="iwyu";
 
-_version="0.1.0";
+_version="0.2.0";
 
 _usage_msg="USAGE: $_as_me [OPTIONS...] [PROJECT-ROOT:=\$PWD] -- \
 [EXTRA-IWYU-ARGS...]
@@ -26,9 +27,6 @@ _help_msg="$_usage_msg
 This explicitly adds the \`-Xiwyu' option to all \`EXTRA-IWYU-ARGS' for
 convenience.
 
-Headers have already been explicitly included with \`--check_also' and can
-be omitted.
-
 A mapping file \`build-aux/iwyu-mappings.json' is automatically applied.
 
 Setting any \`EXTRA-IWYU-ARGS' will override the defaults.
@@ -36,14 +34,17 @@ The default \`EXTRA-IWYU-ARGS' are:
   -Xiwyu --no_comments
 
 OPTIONS
-  -h,--help         Print help message to STDOUT.
-  -u,--usage        Print usage message to STDOUT.
-  -v,--version      Print version information to STDOUT.
+  -t,--tool-opt OPT   Pass an option(s) to \`iwyu_tool.py'
+  -f,--file PATH      Target specific file(s). May be used multiple times.
+  -V,--verbose        Run in verbose mode.
+  -h,--help           Print help message to STDOUT.
+  -u,--usage          Print usage message to STDOUT.
+  -v,--version        Print version information to STDOUT.
 
 ENVIRONMENT
-  IWYU_TOOL         Command used as \`iwyu_tool.py' executable.
-  FIND              Command used as \`find' executable.
-  MAKE              Command used as \`make' executable.
+  IWYU_TOOL           Command used as \`iwyu_tool.py' executable.
+  FIND                Command used as \`find' executable.
+  MAKE                Command used as \`make' executable.
 ";
 
 
@@ -68,7 +69,12 @@ usage() {
 
 # ---------------------------------------------------------------------------- #
 
+_VERBOSE='';
 _PROJECT_ROOT='';
+declare -a _SOURCES;
+_SOURCES=();
+declare -a _iwyu_args;
+_iwyu_args=();
 
 while [[ "$#" -gt 0 ]]; do
   case "$1" in
@@ -94,6 +100,34 @@ while [[ "$#" -gt 0 ]]; do
       unset _arg;
       continue;
     ;;
+    -t|--tool-opt)
+      shift;
+      if [[ "$#" -lt 1 ]]; then
+        echo "$_as_me: Missing argument to \`--tool-opt OPT' option" >&2;
+        usage -f;
+        exit 1;
+      fi
+      # Unquote
+      eval "_iwyu_args+=( $1 )";
+    ;;
+    -f|--file)
+      shift;
+      if [[ "$#" -lt 1 ]]; then
+        echo "$_as_me: Missing argument to \`--file PATH' option" >&2;
+        usage -f;
+        exit 1;
+      fi
+      if ! [[ -f "$1" ]]; then
+        echo "$_as_me: No such file \`--file $1'" >&2;
+        exit 1;
+      fi
+      if ! [[ -r "$1" ]]; then
+        echo "$_as_me: Unable to read \`--file $1'" >&2;
+        exit 1;
+      fi
+      _SOURCES+=( "$1" );
+    ;;
+    -V|--verbose)  _VERBOSE=:; ;;
     -u|--usage)    usage;    exit 0; ;;
     -h|--help)     usage -f; exit 0; ;;
     -v|--version)  echo "$_version"; exit 0; ;;
@@ -154,15 +188,15 @@ fi
 
 # ---------------------------------------------------------------------------- #
 
-# Find all directories with headers.
-declare -a _header_dirs;
-_header_dirs=( $( $FIND "$_PROJECT_ROOT/include" -type d -print; ) );
-
 # Generate arguments for \`iwyu_tool.py':
 
-declare -a _iwyu_args;
-_iwyu_args=(
-  -p "$_PROJECT_ROOT"
+_iwyu_args+=( -p "$_PROJECT_ROOT" );
+
+# Add target file args for `iwyu_tool.py' if they were given.
+if [[ "${#_SOURCES[@]}" -gt 0 ]]; then _iwyu_args+=( "${_SOURCES[@]}" ); fi
+
+# Add `--' separator to begin args for underlying `include-what-you-use' util.
+_iwyu_args+=(  
   --
   -Xiwyu --mapping_file="$_PROJECT_ROOT/build-aux/iwyu-mappings.json"
 );
@@ -174,15 +208,13 @@ for _arg in "${_extra_iwyu_args[@]}"; do
   fi
 done
 
-# Add header directories.
-for _dir in "${_header_dirs[@]}"; do
-  _iwyu_args+=( '-Xiwyu' "--check_also='$_dir/*.hh'" );
-done
-
 
 # ---------------------------------------------------------------------------- #
 
 # Runnit!
+
+# Log command if we're in verbose mode.
+if [[ -n "${_VERBOSE:-}" ]]; then echo "$IWYU_TOOL ${_iwyu_args[*]}" >&2; fi
 
 $IWYU_TOOL "${_iwyu_args[@]}";
 
