emit note for clean files

diff --git a/.github/workflows/clang-tidy.yml b/.github/workflows/clang-tidy.yml
--- a/.github/workflows/clang-tidy.yml
+++ b/.github/workflows/clang-tidy.yml
@@ -139,13 +139,15 @@ jobs:
               sh -c 'clang-tidy "$src"||printf ERROR;' > tidy.log;
               # TODO
               #echo "::warning file=$src,line=0,endLine=0,col=0,endColumn=0,title=Example Warning::This is an example warning";
-              if [[ "$( wc -l ./tidy.log|cut -d' ' -f1; )" -gt 0 ]]; then
-                printf '::warning file=%s,title=Tidy Suggestions::' "$src";
-                ghEscape tidy.log;
-              elif [[ "$( < tidy.log )" = ERROR ]]; then
+              if [[ "$( < tidy.log )" = ERROR ]]; then
                 status=1;
                 printf '::error file=%s,title=clang-tidy Error::%s\n'  \
                        "$src" "Failed to process file \`$src'";
+              elif [[ "$( wc -l ./tidy.log|cut -d' ' -f1; )" -gt 0 ]]; then
+                printf '::warning file=%s,title=Tidy Suggestions::' "$src";
+                ghEscape tidy.log;
+              else
+                echo "clang-tidy generated no suggestions for file \`$src'" >&2;
               fi
               rm -f ./tidy.log;
             done
